import React from 'react'
import CoursesCarousel from './CoursesCarousel';

const courses = [
  {
    id: 10,
    img: "/c1.png",
    title: "100 Days of Code: Python Bootcamp",
    teacher: "Dr. Angela Yu",
    bestseller: true,
    rating: 4.7,
    ratingsCount: 397596,
    newPrice: 519,
    oldPrice: 3109,
    updatedDate: "August 2025",
    totalHours: "56.5",
    level: "All Levels",
    description:
      "Master Python by building 100 projects in 100 days. Learn automation, web, data science, and more!",
    consists: [
      "100 projects in Python",
      "Automation & Web Dev",
      "Machine Learning Basics",
    ],
    courseLink: "/course/10",
    buyLink: "/buy/python-bootcamp",
  },
  {
    id: 11,
    img: "/c2.png",
    title: "The Complete Web Development Bootcamp",
    teacher: "Dr. Angela Yu",
    bestseller: true,
    rating: 4.8,
    ratingsCount: 822451,
    newPrice: 599,
    oldPrice: 3299,
    updatedDate: "September 2025",
    totalHours: "62",
    level: "All Levels",
    description:
      "Learn HTML, CSS, JavaScript, Node.js, React, and MongoDB to become a full-stack web developer.",
    consists: [
      "Frontend + Backend",
      "Deploy real web apps",
      "Hands-on projects",
    ],
    courseLink: "/course/11",
    buyLink: "/buy/web-dev-bootcamp",
  },
  {
    id: 12,
    img: "/c3.png",
    title: "Machine Learning A–Z: AI, Python & R",
    teacher: "Kirill Eremenko",
    bestseller: true,
    rating: 4.6,
    ratingsCount: 535214,
    newPrice: 479,
    oldPrice: 2999,
    updatedDate: "August 2025",
    totalHours: "44",
    level: "Intermediate",
    description:
      "Learn to build powerful machine learning models using Python and R with hands-on projects.",
    consists: [
      "Supervised & Unsupervised ML",
      "Regression & Clustering",
      "AI Real-world examples",
    ],
    courseLink: "/course/12",
    buyLink: "/buy/machine-learning-az",
  },
  {
    id: 13,
    img: "/c4.png",
    title: "The Ultimate React JS Course",
    teacher: "Jonas Schmedtmann",
    bestseller: true,
    rating: 4.9,
    ratingsCount: 452890,
    newPrice: 599,
    oldPrice: 3499,
    updatedDate: "October 2025",
    totalHours: "38",
    level: "All Levels",
    description:
      "Build interactive web apps using React, Redux, and modern hooks from scratch.",
    consists: [
      "React Hooks & State",
      "Context API + Redux",
      "Deploy React apps",
    ],
    courseLink: "/course/13",
    buyLink: "/buy/react-js",
  },
  {
    id: 14,
    img: "/c5.png",
    title: "Data Science Bootcamp 2025",
    teacher: "Jose Portilla",
    bestseller: false,
    rating: 4.7,
    ratingsCount: 312654,
    newPrice: 549,
    oldPrice: 3099,
    updatedDate: "July 2025",
    totalHours: "58",
    level: "All Levels",
    description:
      "Become a data scientist by mastering Python, Pandas, NumPy, Matplotlib, and Seaborn.",
    consists: [
      "Data cleaning & visualization",
      "Statistical analysis",
      "Machine learning basics",
    ],
    courseLink: "/course/14",
    buyLink: "/buy/data-science",
  },
  {
    id: 15,
    img: "/c6.png",
    title: "The Complete Java Developer Bootcamp",
    teacher: "Tim Buchalka",
    bestseller: true,
    rating: 4.7,
    ratingsCount: 276453,
    newPrice: 489,
    oldPrice: 2799,
    updatedDate: "June 2025",
    totalHours: "72",
    level: "Beginner to Advanced",
    description:
      "Master Java programming from basics to advanced topics, including OOP, threads, and file handling.",
    consists: [
      "Java syntax & OOP",
      "Spring Boot intro",
      "Mini projects",
    ],
    courseLink: "/course/15",
    buyLink: "/buy/java-developer",
  },
  {
    id: 16,
    img: "/c7.png",
    title: "Ethical Hacking Masterclass 2025",
    teacher: "Zaid Sabih",
    bestseller: true,
    rating: 4.8,
    ratingsCount: 489601,
    newPrice: 599,
    oldPrice: 3199,
    updatedDate: "September 2025",
    totalHours: "45",
    level: "Intermediate",
    description:
      "Learn ethical hacking from scratch, including network attacks, security testing, and penetration tools.",
    consists: [
      "Network attacks",
      "Wi-Fi security",
      "Real-world exploitation",
    ],
    courseLink: "/course/16",
    buyLink: "/buy/ethical-hacking",
  },
  {
    id: 17,
    img: "/c8.png",
    title: "The Complete Android App Development Course",
    teacher: "Denis Panjuta",
    bestseller: false,
    rating: 4.5,
    ratingsCount: 228900,
    newPrice: 499,
    oldPrice: 2599,
    updatedDate: "May 2025",
    totalHours: "54",
    level: "Beginner",
    description:
      "Learn Android development using Kotlin and build real-world mobile apps.",
    consists: [
      "Kotlin fundamentals",
      "App UI & API usage",
      "Google Play deployment",
    ],
    courseLink: "/course/17",
    buyLink: "/buy/android-development",
  },
  {
    id: 18,
    img: "/Image6.png",
    title: "Artificial Intelligence Masterclass",
    teacher: "Hadelin de Ponteves",
    bestseller: true,
    rating: 4.6,
    ratingsCount: 187562,
    newPrice: 629,
    oldPrice: 3399,
    updatedDate: "October 2025",
    totalHours: "48",
    level: "Advanced",
    description:
      "Learn to build AI models for self-driving cars, voice recognition, and deep learning applications.",
    consists: [
      "Neural networks",
      "Deep learning",
      "AI applications",
    ],
    courseLink: "/course/18",
    buyLink: "/buy/ai-masterclass",
  },
  {
    id: 19,
    img: "/c10.png",
    title: "UI/UX Design from Scratch",
    teacher: "Daniel Walter Scott",
    bestseller: false,
    rating: 4.6,
    ratingsCount: 165231,
    newPrice: 479,
    oldPrice: 2899,
    updatedDate: "July 2025",
    totalHours: "30",
    level: "Beginner",
    description:
      "Master Figma, design systems, and user experience principles to create beautiful digital products.",
    consists: [
      "Figma hands-on design",
      "Color & typography theory",
      "UX project workflow",
    ],
    courseLink: "/course/19",
    buyLink: "/buy/ui-ux-design",
  },
  {
    id: 20,
    img: "/c11.png",
    title: "The Complete SQL & Database Bootcamp",
    teacher: "Jose Portilla",
    bestseller: true,
    rating: 4.8,
    ratingsCount: 395876,
    newPrice: 519,
    oldPrice: 2999,
    updatedDate: "September 2025",
    totalHours: "41",
    level: "All Levels",
    description:
      "Learn SQL from scratch with PostgreSQL and MySQL. Become a database expert and write efficient queries.",
    consists: [
      "SQL fundamentals",
      "Advanced joins & subqueries",
      "Database design",
    ],
    courseLink: "/course/20",
    buyLink: "/buy/sql-bootcamp",
  },
  {
    id: 21,
    img: "/c12.png",
    title: "Complete Cybersecurity & Network Fundamentals",
    teacher: "David Bombal",
    bestseller: true,
    rating: 4.7,
    ratingsCount: 276985,
    newPrice: 549,
    oldPrice: 3099,
    updatedDate: "August 2025",
    totalHours: "52",
    level: "Intermediate",
    description:
      "Understand cybersecurity, firewalls, VPNs, and secure network configurations for real-world protection.",
    consists: [
      "Network setup & security",
      "Firewalls & VPNs",
      "Cyber attack prevention",
    ],
    courseLink: "/course/21",
    buyLink: "/buy/cybersecurity",
  },
];

const Trending = () => {
  return (
    <div>
      <CoursesCarousel title="🔥Trending Courses" courses={courses} />
    </div>
  )
}

export default Trending